import { Level } from '../level'

export default Level.fromLevelString(
  'single player',
  `
(---------------------------------------------------------------)
(                                                               )
(                                                               )
(                                                               )
(                   |------------------------|                  )
(                   |xxxxxxxxxxxxxxxxxxxxxxxx|                  )
(                   |xxxxxxxxxxxxxxxxxxxxxxxx|                  )
(                   |xxxxxxxxxxxxxxxxxxxxxxxx|                  )
(                   |xxxxxxxx|-------|xxxxxxx|                  )
(                   |--------|       |xxxxxxx|                  )
(                                    |xxxxxxx|                  )
(                   |--------|       |xxxxxxx|                  )
(                   |xxxxxxxx|-------|xxxxxxx|                  )
(                   |xxxxxxxxxxxxxxxxxxxxxxxx|                  )
(                   |xxxxxxxxxxxxxxxxxxxxxxxx|                  )
(                   |xxxxxxxxxxxxxxxxxxxxxxxx|                  )
(                   |------------------------|                  )
(                                                               )
(                                                               )
(                                                               )
(           |------------|              |-----------|           )
(           |xxxxxxxxxxxx|              |xxxxxxxxxxx|           )
(           |xxxxxxxxxxxx|              |xxxxxxxxxxx|           )
(           |xxxxxxxxxxxx|              |xxxxxxxxxxx|           )
(           |xxxxxxxxxxxx|              |xxxxxxxxxxx|           )
(           |xxxxxxxxxxxx|              |xxxxxxxxxxx|           )
(           |xxxxxxxxxxxx|              |xxxxxxxxxxx|           )
(           |------------|              |-----------|           )
(         +                                                     )
(                              p                                )
(                                                               )
(                                                               )
(---------------------------------------------------------------)
`
)
